### ISSUE TITLE
button name - need to change from "play composite" to "play utterance" for non-isolated signs

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#193]
This has been changed to display correctly for the "show utterances" window, but not for the main display window - in cases where there are no isolated signs but only examples from the continuous signing corpora.

<img width="540" alt="Screen Shot 2020-01-10 at 12 00 00 PM" src="https://user-images.githubusercontent.com/13629122/72171495-16977f80-33a1-11ea-9d5f-29ba7727caf8.png">

<img width="1034" alt="Screen Shot 2020-01-10 at 11 59 48 AM" src="https://user-images.githubusercontent.com/13629122/72171496-16977f80-33a1-11ea-9bda-e796eb8ebbdc.png">

**Comment by kwasiopoku** [comment]
Fixed

**Comment by cneidle** [comment]
fixed :-). Thank you

**Comment by cneidle** [comment]
This still needs to be changed for the windows that display search results.
<img width="418" alt="Screen Shot 2020-05-05 at 7 59 33 PM" src="https://user-images.githubusercontent.com/13629122/81127162-544d8480-8f0b-11ea-95d2-966099ffb3c0.png">

**Comment by cneidle** [comment]
related to #342

**Comment by cneidle** [comment]
Still a problem - for windows displaying results from searches (using the bottom search options)

<img width="792" alt="Screen Shot 2022-09-03 at 10 55 08 AM" src="https://user-images.githubusercontent.com/13629122/188276173-31b9fe79-0845-4259-9453-1c877a084afb.png">

**Comment by kwasiopoku** [comment]
This has been fixed and pushed to dev1 and dai servers

**Comment by cneidle** [comment]
THANK YOU !
