### ISSUE TITLE
Plus sign not yet completely eliminated from Sign Bank entries; and a few other things

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#275]
DIFFERENT+-arc should not have a + in it...

<img width="142" alt="Screen Shot 2020-12-25 at 12 52 46 PM" src="https://user-images.githubusercontent.com/13629122/103140068-4f169300-46b0-11eb-8e98-748d96c9ce63.png">

Likewise, the + should be eliminated from BUY+*

<img width="161" alt="Screen Shot 2020-12-25 at 12 57 22 PM" src="https://user-images.githubusercontent.com/13629122/103140121-d106bc00-46b0-11eb-8c39-3fbe255fc3b9.png">

And GROW+* should also lose the +

<img width="211" alt="Screen Shot 2020-12-25 at 1 06 17 PM" src="https://user-images.githubusercontent.com/13629122/103140208-15468c00-46b2-11eb-8388-34bbae321100.png">

====

The last entry here should not include the final compound, which should be a separate main entry:

<img width="306" alt="Screen Shot 2020-12-25 at 1 08 06 PM" src="https://user-images.githubusercontent.com/13629122/103140246-5c348180-46b2-11eb-9909-c3b3cc9868e6.png">

====

These entries needs to be permanently removed:

<img width="131" alt="Screen Shot 2020-12-25 at 1 22 03 PM" src="https://user-images.githubusercontent.com/13629122/103140413-4aec7480-46b4-11eb-9f94-09302b4fbdc0.png">

<img width="67" alt="Screen Shot 2020-12-25 at 1 27 51 PM" src="https://user-images.githubusercontent.com/13629122/103140493-0c0aee80-46b5-11eb-88bd-817a6361d73a.png">

<img width="89" alt="Screen Shot 2020-12-25 at 1 35 27 PM" src="https://user-images.githubusercontent.com/13629122/103140565-1679b800-46b6-11eb-84b1-b03eac88479e.png">

<img width="47" alt="Screen Shot 2020-12-25 at 1 36 40 PM" src="https://user-images.githubusercontent.com/13629122/103140578-432dcf80-46b6-11eb-8a1b-d5bee451c1dd.png">

====

Not sure what is going on with sorting.  The main entry, if present among the variants, should be at the top of the list

<img width="195" alt="Screen Shot 2020-12-25 at 1 25 07 PM" src="https://user-images.githubusercontent.com/13629122/103140465-c817e980-46b4-11eb-94db-4978d0292c0d.png">

====

TELL:i. and TELL:j should be merged

<img width="132" alt="Screen Shot 2020-12-25 at 1 32 08 PM" src="https://user-images.githubusercontent.com/13629122/103140537-ad924000-46b5-11eb-95af-f9febe78e111.png">
====

These two variants should be distinct main entries:

<img width="140" alt="Screen Shot 2020-12-25 at 1 33 13 PM" src="https://user-images.githubusercontent.com/13629122/103140551-d0bcef80-46b5-11eb-9bee-1af37c2d999d.png">

**Comment by kwasiopoku** [comment]
Everything on this ticket has been fixed with the exception of the sorting of "PAY"

**Comment by cneidle** [comment]
Thank you so much !!!!!

This one also remains to be resolved:

<img width="683" alt="Screen Shot 2021-01-10 at 8 48 33 AM" src="https://user-images.githubusercontent.com/13629122/104124803-b70be100-5320-11eb-94b5-a1decbc51375.png">


THANK YOU.

**Comment by cneidle** [comment]
Here is another one with a + sign that should not be there:  

<img width="87" alt="Screen Shot 2021-01-12 at 1 50 56 PM" src="https://user-images.githubusercontent.com/13629122/104360281-d05a8c00-54de-11eb-8619-a6e2d2621fb0.png">

**Comment by cneidle** [comment]
Here are some other entries that need to be permanently deleted:

<img width="165" alt="Screen Shot 2021-01-12 at 1 59 32 PM" src="https://user-images.githubusercontent.com/13629122/104360402-fe3fd080-54de-11eb-8e3b-7681a0da7aa3.png">

<img width="134" alt="Screen Shot 2021-01-12 at 1 57 59 PM" src="https://user-images.githubusercontent.com/13629122/104360417-0566de80-54df-11eb-86cf-0a3a29e90229.png">


<img width="73" alt="Screen Shot 2021-01-12 at 1 39 09 PM" src="https://user-images.githubusercontent.com/13629122/104360454-13b4fa80-54df-11eb-8a7f-06a909fb1aa3.png">


=========

This one actually is a sign that we just don't happen to have any examples of.
So the entry can be left in the spreadsheet, but until we get an example of it, it should not
be displayed:

<img width="123" alt="Screen Shot 2021-01-12 at 1 44 08 PM" src="https://user-images.githubusercontent.com/13629122/104360443-0e57b000-54df-11eb-9b54-bb471219fa3b.png">

**Comment by cneidle** [comment]
Plus signs still showing up in the list...

<img width="138" alt="Screen Shot 2021-02-21 at 11 26 46 AM" src="https://user-images.githubusercontent.com/13629122/108631393-d4f85580-7437-11eb-84da-c8d09ab8c1a2.png">

**Comment by cneidle** [comment]
This seems to be resolved now.

**Comment by kwasiopoku** [comment]
This issue is still occurring on the dev1.  We will updated the variants manually and review the parser to ensure that the correct auto classification logic is applied to all agreement markers

**Comment by cneidle** [comment]
The top issue i s still present - still showing a +. with DIFFERENT.

<img width="238" alt="Screen Shot 2022-03-12 at 4 23 03 PM" src="https://user-images.githubusercontent.com/13629122/158035482-b466bafc-662d-40c1-bd24-d1b479b472c8.png">

**Comment by cneidle** [comment]
different+-arc has been fixed manually.  thank you!
but we need to adjust the algorithm for the future.

**Comment by cneidle** [comment]
The problem with different+-arc has returned!

<img width="150" alt="Screen Shot 2022-10-24 at 9 33 39 AM" src="https://user-images.githubusercontent.com/13629122/197538425-08d7cafe-6ee3-48db-ada6-9e47248a4e54.png">

**Comment by cneidle** [comment]
Still has not been fixed.

**Comment by kwasiopoku** [comment]
I have updated these on dev one but I will recheck once I re-upload all the updated collections.  Longer term, we need to fix the video parser

**Comment by cneidle** [comment]
Thank you!

I have deleted that sign from the 5 RIT files where it occurred.

So if you delete the sign from the ASLLVD, we won’t have to
worry about this again :-)

THANKS,
 Carol

**Comment by cneidle** [comment]
The problem with +-arc remains:

<img width="155" alt="Screen Shot 2022-11-20 at 1 06 26 PM" src="https://user-images.githubusercontent.com/13629122/202918344-64de3032-6f18-4043-91ea-36ca857d5012.png">

**Comment by kwasiopoku** [comment]
This has been fixed on dev1

**Comment by cneidle** [comment]
fixed - thanks!
