### ISSUE TITLE
problems with special characters

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/ASL-DAI#339]
There seems to be a problem with some apostrophes

<img width="487" alt="Screen Shot 2022-08-16 at 2 03 04 PM" src="https://user-images.githubusercontent.com/13629122/184948243-33c93f0e-a719-4c07-930c-27bcf4cca6fd.png">

seems to be fixed -CN, 10/14

Also, commas inside gesture glosses seems to throw off the export to the English words spreadsheet.  Not sure if it's creating problems elsewhere.

<img width="920" alt="Screen Shot 2022-08-16 at 2 04 33 PM" src="https://user-images.githubusercontent.com/13629122/184948425-e5991415-6126-4bf2-b532-18b8ff198cd9.png">

Problem with œ

<img width="517" alt="Screen Shot 2022-08-16 at 2 06 16 PM" src="https://user-images.githubusercontent.com/13629122/184948718-468c4ae3-c72e-4542-b3f2-15e43f4e9c8f.png">

seems to be fixed -CN, 10/14

**Comment by cneidle** [comment]
<img width="905" alt="Screen Shot 2022-08-16 at 7 25 16 PM" src="https://user-images.githubusercontent.com/13629122/185002426-fdf27fc5-5b64-4c53-a734-b8866610d7c9.png">

The main entry for these two lines should be the same, but the top one is missing.

**Comment by cneidle** [comment]
Not sure that this has anything to do with special characters, but this sign is listed twice, for some reason, in the English words spreadsheet.

<img width="900" alt="Screen Shot 2022-08-16 at 7 29 23 PM" src="https://user-images.githubusercontent.com/13629122/185002535-65a093ff-8c53-4cdf-b17a-4b7cb4e72f9a.png">

**Comment by cneidle** [comment]
first and third lines should presumably be the same ?

<img width="428" alt="Screen Shot 2022-08-16 at 7 35 18 PM" src="https://user-images.githubusercontent.com/13629122/185003044-cd1e5ed9-8755-48e7-980d-db42319d54d0.png">

Note that this is what appears in the DAI.  I looked at the sign in the singleton instance, utterance 12 of Deaf Grunts, and I don't see ay difference in the characters.

<img width="768" alt="Screen Shot 2022-08-17 at 4 20 58 PM" src="https://user-images.githubusercontent.com/13629122/185235661-ec1354c6-6a4a-4e05-95f1-028ab380caf0.png">

does NOT appear to be fixed - CN, 10/13

**Comment by cneidle** [comment]
also problem with ï

<img width="852" alt="Screen Shot 2022-08-17 at 10 33 32 AM" src="https://user-images.githubusercontent.com/13629122/185163068-c10a7c67-358d-4f87-87b0-619d512355dc.png">

**Comment by cneidle** [comment]
another problem - should be "

<img width="343" alt="Screen Shot 2022-08-17 at 12 24 23 PM" src="https://user-images.githubusercontent.com/13629122/185192433-9050d16e-5a03-4961-b413-d7758efb8dad.png">

<img width="1201" alt="Screen Shot 2022-08-17 at 12 24 16 PM" src="https://user-images.githubusercontent.com/13629122/185192436-968ca008-d2e2-4d83-b0b8-95ab401fd16b.png">

**Comment by cneidle** [comment]
same as above


<img width="344" alt="Screen Shot 2022-08-17 at 1 28 18 PM" src="https://user-images.githubusercontent.com/13629122/185204027-622b69cb-9a08-4151-8bdd-d4f73336a208.png">


<img width="315" alt="Screen Shot 2022-08-17 at 1 28 12 PM" src="https://user-images.githubusercontent.com/13629122/185204031-fc827669-e02a-4147-acb1-0eb1b1934b9c.png">


seems to be fixed -CN, 10/14

**Comment by cneidle** [comment]
another example with ' and ""

<img width="318" alt="Screen Shot 2022-08-17 at 1 32 29 PM" src="https://user-images.githubusercontent.com/13629122/185204819-55961024-d345-464b-87ec-b57c0bb5a97b.png">

<img width="530" alt="Screen Shot 2022-08-17 at 1 32 16 PM" src="https://user-images.githubusercontent.com/13629122/185204856-4c719137-a3cd-4ea7-888c-480e03b47ccc.png">

seems to be fixed -CN, 10/14

**Comment by cneidle** [comment]
one more:

<img width="231" alt="Screen Shot 2022-08-17 at 5 50 56 PM" src="https://user-images.githubusercontent.com/13629122/185249726-f982054c-b92d-47c0-81c3-6057ef756f05.png">

<img width="532" alt="Screen Shot 2022-08-17 at 5 49 56 PM" src="https://user-images.githubusercontent.com/13629122/185249727-b001f223-485a-4a4c-923e-02676e6e1220.png">

seems to be fixed -CN, 10/14

**Comment by cneidle** [comment]
Some examples of special character problems in the DAI

There should not be any question marks displayed.  The problems involve especially ' and "

<img width="131" alt="Screen Shot 2022-08-17 at 9 17 41 PM" src="https://user-images.githubusercontent.com/13629122/185270991-9b6b684c-c6ae-4540-bb0c-806dbd72d093.png">

<img width="173" alt="Screen Shot 2022-08-17 at 9 17 17 PM" src="https://user-images.githubusercontent.com/13629122/185270992-32aab8b2-c372-4d76-abab-065d61a81a85.png">

<img width="171" alt="Screen Shot 2022-08-17 at 9 17 11 PM" src="https://user-images.githubusercontent.com/13629122/185270993-c97a4971-93a8-4302-a760-b133315028a4.png">

<img width="180" alt="Screen Shot 2022-08-17 at 9 17 05 PM" src="https://user-images.githubusercontent.com/13629122/185270994-0644cd06-b3ca-40ec-afc2-0a5aaeb2c2f3.png">

seems to be fixed -CN, 10/14

**Comment by cneidle** [comment]
see also #127

**Comment by kwasiopoku** [comment]
These have been fixed on dev1.cs

**Comment by cneidle** [comment]
THE ONE REMAINING ITEM seems to be the "whoa" case above.  Thanks.

**Comment by kwasiopoku** [comment]
I believe this has been resolved on dev1.  Can you please confirm?

**Comment by cneidle** [comment]
yes!  thank you !!

**Comment by cneidle** [comment]
There are still issues with special characters in the DAI,  e.g. these question marks:

<img width="139" alt="Screen Shot 2022-11-11 at 4 22 05 PM" src="https://user-images.githubusercontent.com/13629122/201432689-a308e27c-aa88-44ac-acee-b927c164a50c.png">

**Comment by cneidle** [comment]
still needs to be fixed

**Comment by cneidle** [comment]
Still a problem also with special characters in the Sign Bank gestures 

<img width="154" alt="Screen Shot 2023-01-09 at 4 34 43 PM" src="https://user-images.githubusercontent.com/13629122/211413057-44eac0bf-8371-456e-82db-1f561bac8384.png">

**Comment by cneidle** [comment]
These are mostly fixed, but here is one example of a problem that remains on the DAI 

<img width="195" alt="Screen Shot 2023-12-03 at 11 37 30 AM" src="https://github.com/DCS-LCSR/ASL-DAI/assets/13629122/ca9a4765-ae0d-4608-9fec-c462b33dfacf">

**Comment by kwasiopoku** [comment]
This has been resolved on dev1.cs and dai.cs
